### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by Aladdin1234** [danielarndt/flowtbag#6]
Hello Daniel,
I'm just starting to use flowtbag, everything is fine with small pcap files, but when i use pcap files with  big size (like 20 MB or more) I get this issues:
panic: runtime error: index out of range
goroutine 1 [running]:
main.process(0xf840028060, 0xf840028060)
	/home/darndt/git/flowtbag/src/flowtbag.go:148 +0x2fd
main.main()
	/home/darndt/git/flowtbag/src/flowtbag.go:109 +0x31f
I made searches in the internet but i found nothing.
Please any help bro, I want to know if the size of files is the problem or not, thanks in advance.

**Comment by DanielArndt** [comment]
Large files shouldn't be a problem. Are you able to share a capture file that causes the issue? (Please make sure it has no personal information before doing so)

**Comment by Aladdin1234** [comment]
hi bro, thanks for responding,
i will send it to you by gmail if you dont mind.

**Comment by Aladdin1234** [comment]
> Large files shouldn't be a problem. Are you able to share a capture file that causes the issue? (Please make sure it has no personal information before doing so)

I sent it bro.

**Comment by Aladdin1234** [comment]
Hello Daniel,
The flow in this pcap is not bi-directional.
I want to ask here if  there is a possibility to apply flowtbag on this pcap file, and if we can do this,  there will be changes in the source code or we build it from zero. Thanks in advance.

**Comment by DanielArndt** [comment]
My apologies, I was travelling and unable to take a look. You closed the issue, so have you solved your issue?

If so, I'm interested to know what was wrong.

**Comment by Aladdin1234** [comment]
No problem Daniel, 
The pcap file contains unidirectional flow and in the source code of flowtbag i found that flow.go require bidirectional flow, so firstly i tried to modify the code to get a result, but next i just decided to move on to another flow analyzer and now it works fine with it. So thank you for your time and for your respond.

**Comment by DanielArndt** [comment]
Oh, yes it does require bi-directional. I'm glad you were able to figure that out, and sorry it wasted a bit of your time. Good to hear you found something else that will work though!
